#ifndef INSTRS_H__
#define INSTRS_H__ 1

/* DO NOT EDIT!
 *
 * This file is created automatically by make_func from
 * the specifications in func_spec.
 *
 * It holds the bytecode values for all machine instructions, plus
 * declarations of the tables holding information about the instructions.
 */

#include "exec.h"  /* struct instr_s == instr_t */

#define CODE_OFFSET  (0)
#define CODE_COUNT   (223)
  /* First offset and number of internal opcodes.
   */

#define EFUN_OFFSET  (223)
#define EFUN_COUNT   (26)
  /* First offset and number of efun opcodes.
   */

#define EFUN0_OFFSET  (249)
#define EFUN0_COUNT   (14)
  /* First offset and number of efun0 opcodes.
   */

#define EFUN1_OFFSET  (263)
#define EFUN1_COUNT   (84)
  /* First offset and number of efun1 opcodes.
   */

#define EFUN2_OFFSET  (347)
#define EFUN2_COUNT   (52)
  /* First offset and number of efun2 opcodes.
   */

#define EFUN3_OFFSET  (399)
#define EFUN3_COUNT   (13)
  /* First offset and number of efun3 opcodes.
   */

#define EFUN4_OFFSET  (412)
#define EFUN4_COUNT   (1)
  /* First offset and number of efun4 opcodes.
   */

#define EFUNV_OFFSET  (413)
#define EFUNV_COUNT   (75)
  /* First offset and number of efunv opcodes.
   */

#define LAST_INSTRUCTION_CODE (487)
  /* The highest token value in use.
   */

#define TEFUN_OFFSET EFUN0_OFFSET
  /* Offset of the first tabled efun.
   */

extern instr_t instrs[];
extern short efun_aliases[];
extern fulltype_t efun_arg_types[];
extern long efun_lpc_types[];
extern svalue_t *(*efun_table[])(svalue_t *);
extern svalue_t *(*vefun_table[])(svalue_t *, int);
  /* All tables are defined in efun_defs.c and compiled into lex.c
   * TODO: We might as well create efun_defs.h and compile it separately.
   */

/* --- codes --- */

#define F_ILLEGAL                      (0)
#define F_UNDEF                        (1)
#define F_EFUN0                        (2)
#define F_EFUN1                        (3)
#define F_EFUN2                        (4)
#define F_EFUN3                        (5)
#define F_EFUN4                        (6)
#define F_EFUNV                        (7)
#define F_IDENTIFIER                   (8)
#define F_STRING                       (9)
#define F_CSTRING0                     (10)
#define F_CSTRING1                     (11)
#define F_CSTRING2                     (12)
#define F_CSTRING3                     (13)
#define F_NUMBER                       (14)
#define F_CONST0                       (15)
#define F_CONST1                       (16)
#define F_NCONST1                      (17)
#define F_CLIT                         (18)
#define F_NCLIT                        (19)
#define F_FCONST0                      (20)
#define F_FLOAT                        (21)
#define F_CLOSURE                      (22)
#define F_SYMBOL                       (23)
#define F_RETURN                       (24)
#define F_RETURN0                      (25)
#define F_DEFAULT_RETURN               (26)
#define F_BREAK                        (27)
#define F_SWITCH                       (28)
#define F_LOCAL                        (29)
#define F_CATCH                        (30)
#define F_INC                          (31)
#define F_DEC                          (32)
#define F_POST_INC                     (33)
#define F_POST_DEC                     (34)
#define F_PRE_INC                      (35)
#define F_PRE_DEC                      (36)
#define F_LAND                         (37)
#define F_LOR                          (38)
#define F_ASSIGN                       (39)
#define F_VOID_ASSIGN                  (40)
#define F_ADD                          (41)
#define F_SUBTRACT                     (42)
#define F_MULTIPLY                     (43)
#define F_DIVIDE                       (44)
#define F_MOD                          (45)
#define F_GT                           (46)
#define F_GE                           (47)
#define F_LT                           (48)
#define F_LE                           (49)
#define F_EQ                           (50)
#define F_NE                           (51)
#define F_IN                           (52)
#define F_COMPL                        (53)
#define F_AND                          (54)
#define F_OR                           (55)
#define F_XOR                          (56)
#define F_LSH                          (57)
#define F_RSH                          (58)
#define F_RSHL                         (59)
#define F_NOT                          (60)
#define F_INDEX                        (61)
#define F_RINDEX                       (62)
#define F_AINDEX                       (63)
#define F_MAP_INDEX                    (64)
#define F_MAP_RINDEX                   (65)
#define F_MAP_AINDEX                   (66)
#define F_S_INDEX                      (67)
#define F_SX_INDEX                     (68)
#define F_RANGE                        (69)
#define F_NR_RANGE                     (70)
#define F_RN_RANGE                     (71)
#define F_RR_RANGE                     (72)
#define F_NA_RANGE                     (73)
#define F_RA_RANGE                     (74)
#define F_AN_RANGE                     (75)
#define F_AR_RANGE                     (76)
#define F_AA_RANGE                     (77)
#define F_NX_RANGE                     (78)
#define F_RX_RANGE                     (79)
#define F_AX_RANGE                     (80)
#define F_MAP_RANGE                    (81)
#define F_MAP_NR_RANGE                 (82)
#define F_MAP_RN_RANGE                 (83)
#define F_MAP_RR_RANGE                 (84)
#define F_MAP_NA_RANGE                 (85)
#define F_MAP_RA_RANGE                 (86)
#define F_MAP_AN_RANGE                 (87)
#define F_MAP_AR_RANGE                 (88)
#define F_MAP_AA_RANGE                 (89)
#define F_MAP_NX_RANGE                 (90)
#define F_MAP_RX_RANGE                 (91)
#define F_MAP_AX_RANGE                 (92)
#define F_VOID_ADD_EQ                  (93)
#define F_ADD_EQ                       (94)
#define F_SUB_EQ                       (95)
#define F_DIV_EQ                       (96)
#define F_MULT_EQ                      (97)
#define F_MOD_EQ                       (98)
#define F_AND_EQ                       (99)
#define F_OR_EQ                        (100)
#define F_XOR_EQ                       (101)
#define F_LSH_EQ                       (102)
#define F_RSH_EQ                       (103)
#define F_RSHL_EQ                      (104)
#define F_LAND_EQ                      (105)
#define F_LOR_EQ                       (106)
#define F_POP_VALUE                    (107)
#define F_POP_SECOND                   (108)
#define F_DUP                          (109)
#define F_LDUP                         (110)
#define F_SWAP_VALUES                  (111)
#define F_CLEAR_LOCALS                 (112)
#define F_SAVE_ARG_FRAME               (113)
#define F_RESTORE_ARG_FRAME            (114)
#define F_USE_ARG_FRAME                (115)
#define F_FLATTEN_XARG                 (116)
#define F_FBRANCH                      (117)
#define F_LBRANCH                      (118)
#define F_LBRANCH_WHEN_ZERO            (119)
#define F_LBRANCH_WHEN_NON_ZERO        (120)
#define F_BRANCH                       (121)
#define F_BRANCH_WHEN_ZERO             (122)
#define F_BRANCH_WHEN_NON_ZERO         (123)
#define F_BBRANCH_WHEN_ZERO            (124)
#define F_BBRANCH_WHEN_NON_ZERO        (125)
#define F_CALL_FUNCTION                (126)
#define F_CALL_INHERITED               (127)
#define F_CALL_INHERITED_NOARGS        (128)
#define F_CALL_CLOSURE                 (129)
#define F_CONTEXT_CLOSURE              (130)
#define F_CONTEXT_LAMBDA               (131)
#define F_CONTEXT_IDENTIFIER           (132)
#define F_TRANSFORM_TO_COROUTINE       (133)
#define F_AWAIT                        (134)
#define F_YIELD_TO_COROUTINE           (135)
#define F_YIELD_RETURN                 (136)
#define F_PUSH_CONTEXT_LVALUE          (137)
#define F_CONTEXT_IDENTIFIER16         (138)
#define F_PUSH_CONTEXT16_LVALUE        (139)
#define F_PUSH_IDENTIFIER_LVALUE       (140)
#define F_VIRTUAL_VARIABLE             (141)
#define F_PUSH_VIRTUAL_VARIABLE_LVALUE (142)
#define F_IDENTIFIER16                 (143)
#define F_PUSH_IDENTIFIER16_LVALUE     (144)
#define F_PUSH_LOCAL_VARIABLE_LVALUE   (145)
#define F_INDEX_LVALUE                 (146)
#define F_RINDEX_LVALUE                (147)
#define F_AINDEX_LVALUE                (148)
#define F_S_INDEX_LVALUE               (149)
#define F_SX_INDEX_LVALUE              (150)
#define F_RANGE_LVALUE                 (151)
#define F_NR_RANGE_LVALUE              (152)
#define F_RN_RANGE_LVALUE              (153)
#define F_RR_RANGE_LVALUE              (154)
#define F_NA_RANGE_LVALUE              (155)
#define F_RA_RANGE_LVALUE              (156)
#define F_AN_RANGE_LVALUE              (157)
#define F_AR_RANGE_LVALUE              (158)
#define F_AA_RANGE_LVALUE              (159)
#define F_NX_RANGE_LVALUE              (160)
#define F_RX_RANGE_LVALUE              (161)
#define F_AX_RANGE_LVALUE              (162)
#define F_MAP_INDEX_LVALUE             (163)
#define F_MAP_RINDEX_LVALUE            (164)
#define F_MAP_AINDEX_LVALUE            (165)
#define F_MAP_RANGE_LVALUE             (166)
#define F_MAP_NR_RANGE_LVALUE          (167)
#define F_MAP_RN_RANGE_LVALUE          (168)
#define F_MAP_RR_RANGE_LVALUE          (169)
#define F_MAP_NA_RANGE_LVALUE          (170)
#define F_MAP_RA_RANGE_LVALUE          (171)
#define F_MAP_AN_RANGE_LVALUE          (172)
#define F_MAP_AR_RANGE_LVALUE          (173)
#define F_MAP_AA_RANGE_LVALUE          (174)
#define F_MAP_NX_RANGE_LVALUE          (175)
#define F_MAP_RX_RANGE_LVALUE          (176)
#define F_MAP_AX_RANGE_LVALUE          (177)
#define F_MAKE_PROTECTED               (178)
#define F_MAKE_RVALUE                  (179)
#define F_PUSH_VIRTUAL_VARIABLE_VLVALUE (180)
#define F_PUSH_IDENTIFIER_VLVALUE      (181)
#define F_PUSH_IDENTIFIER16_VLVALUE    (182)
#define F_PUSH_CONTEXT_VLVALUE         (183)
#define F_PUSH_LOCAL_VARIABLE_VLVALUE  (184)
#define F_INDEX_VLVALUE                (185)
#define F_RINDEX_VLVALUE               (186)
#define F_AINDEX_VLVALUE               (187)
#define F_S_INDEX_VLVALUE              (188)
#define F_SX_INDEX_VLVALUE             (189)
#define F_MAP_INDEX_VLVALUE            (190)
#define F_MAP_RINDEX_VLVALUE           (191)
#define F_MAP_AINDEX_VLVALUE           (192)
#define F_SIMUL_EFUN                   (193)
#define F_AGGREGATE                    (194)
#define F_M_AGGREGATE                  (195)
#define F_M_CAGGREGATE                 (196)
#define F_S_AGGREGATE                  (197)
#define F_S_M_AGGREGATE                (198)
#define F_PREVIOUS_OBJECT0             (199)
#define F_LAMBDA_CCONSTANT             (200)
#define F_LAMBDA_CONSTANT              (201)
#define F_FOREACH                      (202)
#define F_FOREACH_REF                  (203)
#define F_FOREACH_RANGE                (204)
#define F_FOREACH_NEXT                 (205)
#define F_FOREACH_END                  (206)
#define F_END_CATCH                    (207)
#define F_BREAK_CONTINUE               (208)
#define F_BREAKN_CONTINUE              (209)
#define F_JUMP                         (210)
#define F_NO_WARN_DEPRECATED           (211)
#define F_ARRAY_RANGE_CHECK            (212)
#define F_ARRAY0                       (213)
#define F_MOVE_VALUE                   (214)
#define F_DUP_N                        (215)
#define F_POP_N                        (216)
#define F_PUT_ARRAY_ELEMENT            (217)
#define F_TYPE_CHECK                   (218)
#define F_LAMBDA_TYPE_CHECK            (219)
#define F_PUSH_TYPE                    (220)
#define F_CALL_OTHER_CACHED            (221)
#define F_CALL_STRICT_CACHED           (222)

/* --- efuns --- */

#define F_BYTESP                       (223)
#define F_CLONEP                       (224)
#define F_CLOSUREP                     (225)
#define F_COROUTINEP                   (226)
#define F_EXTERN_CALL                  (227)
#define F_FLOATP                       (228)
#define F_INTP                         (229)
#define F_LPCTYPEP                     (230)
#define F_LWOBJECTP                    (231)
#define F_MAPPINGP                     (232)
#define F_MASTER                       (233)
#define F_NEGATE                       (234)
#define F_OBJECTP                      (235)
#define F_POINTERP                     (236)
#define F_RAISE_ERROR                  (237)
#define F_REFERENCEP                   (238)
#define F_SIZEOF                       (239)
#define F_STRINGP                      (240)
#define F_STRUCTP                      (241)
#define F_SYMBOLP                      (242)
#define F_THIS_COROUTINE               (243)
#define F_THIS_INTERACTIVE             (244)
#define F_THIS_OBJECT                  (245)
#define F_THIS_PLAYER                  (246)
#define F_THROW                        (247)
#define F_TYPEOF                       (248)

/* --- efun0s --- */

#define F_CALL_OUT_INFO                (249)
#define F_CALLER_STACK_DEPTH           (250)
#define F_COMMAND_STACK                (251)
#define F_COMMAND_STACK_DEPTH          (252)
#define F_GET_EVAL_COST                (253)
#define F_HEART_BEAT_INFO              (254)
#define F_QUERY_COMMAND                (255)
#define F_REGEXP_PACKAGE               (256)
#define F_RUSAGE                       (257)
#define F_TIME                         (258)
#define F_UNSHADOW                     (259)
#define F_USERS                        (260)
#define F_UTIME                        (261)
#define F_WIZLIST_INFO                 (262)

/* --- efun1s --- */

#define F_ABS                          (263)
#define F_ACOS                         (264)
#define F_ALL_INVENTORY                (265)
#define F_ASIN                         (266)
#define F_ATAN                         (267)
#define F_BLUEPRINT                    (268)
#define F_CALLER_STACK                 (269)
#define F_CAPITALIZE                   (270)
#define F_CEIL                         (271)
#define F_COPY                         (272)
#define F_COS                          (273)
#define F_COUNT_BITS                   (274)
#define F_CTIME                        (275)
#define F_DEEP_COPY                    (276)
#define F_DESTRUCT                     (277)
#define F_DRIVER_INFO                  (278)
#define F_EXP                          (279)
#define F_FILE_SIZE                    (280)
#define F_FIND_CALL_OUT                (281)
#define F_FIND_OBJECT                  (282)
#define F_FIRST_INVENTORY              (283)
#define F_FLOOR                        (284)
#define F_GET_EXTRA_WIZINFO            (285)
#define F_GETEUID                      (286)
#define F_GETUID                       (287)
#define F_GMTIME                       (288)
#define F_INPUT_TO_INFO                (289)
#define F_INTERACTIVE                  (290)
#define F_INVERT_BITS                  (291)
#define F_LAST_BIT                     (292)
#define F_LIVING                       (293)
#define F_LOAD_NAME                    (294)
#define F_LOAD_OBJECT                  (295)
#define F_LOCALTIME                    (296)
#define F_LOG                          (297)
#define F_LOWER_CASE                   (298)
#define F_M_INDICES                    (299)
#define F_MAKE_SHARED_STRING           (300)
#define F_MKDIR                        (301)
#define F_MKTIME                       (302)
#define F_NEXT_INVENTORY               (303)
#define F_NOTIFY_FAIL                  (304)
#define F_OBJECT_NAME                  (305)
#define F_OBJECT_TIME                  (306)
#define F_PREVIOUS_OBJECT              (307)
#define F_PROCESS_STRING               (308)
#define F_PROGRAM_NAME                 (309)
#define F_PROGRAM_TIME                 (310)
#define F_QUERY_NOTIFY_FAIL            (311)
#define F_QUERY_VERB                   (312)
#define F_QUOTE                        (313)
#define F_RANDOM                       (314)
#define F_REMOVE_CALL_OUT              (315)
#define F_REMOVE_INTERACTIVE           (316)
#define F_RESTORE_OBJECT               (317)
#define F_RESTORE_VALUE                (318)
#define F_REVERSE                      (319)
#define F_RM                           (320)
#define F_RMDIR                        (321)
#define F_SET_NEXT_RESET               (322)
#define F_SET_THIS_OBJECT              (323)
#define F_SET_THIS_PLAYER              (324)
#define F_SGN                          (325)
#define F_SHADOW                       (326)
#define F_SHUTDOWN                     (327)
#define F_SIN                          (328)
#define F_SQRT                         (329)
#define F_SYMBOL_VARIABLE              (330)
#define F_TAN                          (331)
#define F_TEXT_WIDTH                   (332)
#define F_TO_ARRAY                     (333)
#define F_TO_FLOAT                     (334)
#define F_TO_INT                       (335)
#define F_TO_LPCTYPE                   (336)
#define F_TO_OBJECT                    (337)
#define F_TO_STRING                    (338)
#define F_TRACE                        (339)
#define F_TRACEPREFIX                  (340)
#define F_TRANSPOSE_ARRAY              (341)
#define F_UNMKMAPPING                  (342)
#define F_UNQUOTE                      (343)
#define F_UPPER_CASE                   (344)
#define F_WIDTHOF                      (345)
#define F_WRITE                        (346)

/* --- efun2s --- */

#define F_AND_BITS                     (347)
#define F_ATAN2                        (348)
#define F_ATTACH_ERQ_DEMON             (349)
#define F_BASEOF                       (350)
#define F_BINARY_MESSAGE               (351)
#define F_CALL_COROUTINE               (352)
#define F_CHECK_TYPE                   (353)
#define F_CLEAR_BIT                    (354)
#define F_CONFIGURE_DRIVER             (355)
#define F_COPY_FILE                    (356)
#define F_CRYPT                        (357)
#define F_DEBUG_MESSAGE                (358)
#define F_DUMP_DRIVER_INFO             (359)
#define F_EXEC                         (360)
#define F_EXPAND_DEFINE                (361)
#define F_EXPLODE                      (362)
#define F_FUNCTIONLIST                 (363)
#define F_GET_DIR                      (364)
#define F_GET_ERROR_FILE               (365)
#define F_IMPLODE                      (366)
#define F_INTERACTIVE_INFO             (367)
#define F_LAMBDA                       (368)
#define F_LAST_INSTRUCTIONS            (369)
#define F_LWOBJECT_INFO                (370)
#define F_M_ALLOCATE                   (371)
#define F_M_DELETE                     (372)
#define F_M_ENTRY                      (373)
#define F_M_REALLOCATE                 (374)
#define F_M_VALUES                     (375)
#define F_MATCH_COMMAND                (376)
#define F_MD5_CRYPT                    (377)
#define F_MOVE_OBJECT                  (378)
#define F_NET_CONNECT                  (379)
#define F_OBJECT_INFO                  (380)
#define F_OR_BITS                      (381)
#define F_POW                          (382)
#define F_QUERY_ACTIONS                (383)
#define F_REMOVE_ACTION                (384)
#define F_RENAME                       (385)
#define F_RENAME_OBJECT                (386)
#define F_SET_BIT                      (387)
#define F_SET_DRIVER_HOOK              (388)
#define F_SET_ENVIRONMENT              (389)
#define F_SET_EXTRA_WIZINFO            (390)
#define F_STRUCT_INFO                  (391)
#define F_SYMBOL_FUNCTION              (392)
#define F_TELL_OBJECT                  (393)
#define F_TEST_BIT                     (394)
#define F_TRANSFER                     (395)
#define F_UNBOUND_LAMBDA               (396)
#define F_VARIABLE_LIST                (397)
#define F_XOR_BITS                     (398)

/* --- efun3s --- */

#define F_CONFIGURE_INTERACTIVE        (399)
#define F_CONFIGURE_LWOBJECT           (400)
#define F_CONFIGURE_OBJECT             (401)
#define F_EXECUTE_COMMAND              (402)
#define F_HMAC                         (403)
#define F_NEXT_BIT                     (404)
#define F_REGEXP                       (405)
#define F_REGEXPLODE                   (406)
#define F_SEND_ERQ                     (407)
#define F_SEND_UDP                     (408)
#define F_STRRSTR                      (409)
#define F_STRSTR                       (410)
#define F_WRITE_BYTES                  (411)

/* --- efun4s --- */

#define F_REGREPLACE                   (412)

/* --- vefuns --- */

#define F_ADD_ACTION                   (413)
#define F_ALL_ENVIRONMENT              (414)
#define F_ALLOCATE                     (415)
#define F_APPLY                        (416)
#define F_BIND_LAMBDA                  (417)
#define F_CALL_DIRECT                  (418)
#define F_CALL_DIRECT_RESOLVED         (419)
#define F_CALL_DIRECT_STRICT           (420)
#define F_CALL_OTHER                   (421)
#define F_CALL_OUT                     (422)
#define F_CALL_RESOLVED                (423)
#define F_CALL_STRICT                  (424)
#define F_CLONE_OBJECT                 (425)
#define F_CLONES                       (426)
#define F_COMMAND                      (427)
#define F_COMPILE_STRING               (428)
#define F_COPY_BITS                    (429)
#define F_DEEP_INVENTORY               (430)
#define F_ED                           (431)
#define F_ENVIRONMENT                  (432)
#define F_FILTER                       (433)
#define F_FILTER_INDICES               (434)
#define F_FILTER_OBJECTS               (435)
#define F_FIND_INPUT_TO                (436)
#define F_FUNCALL                      (437)
#define F_FUNCTION_EXISTS              (438)
#define F_GARBAGE_COLLECTION           (439)
#define F_GET_TYPE_INFO                (440)
#define F_HASH                         (441)
#define F_INCLUDE_LIST                 (442)
#define F_INHERIT_LIST                 (443)
#define F_INPUT_TO                     (444)
#define F_LIMITED                      (445)
#define F_M_ADD                        (446)
#define F_M_CONTAINS                   (447)
#define F_MAP                          (448)
#define F_MAP_INDICES                  (449)
#define F_MAP_OBJECTS                  (450)
#define F_MAX                          (451)
#define F_MD5                          (452)
#define F_MEMBER                       (453)
#define F_MIN                          (454)
#define F_MKMAPPING                    (455)
#define F_NEW_LWOBJECT                 (456)
#define F_OBJECTS                      (457)
#define F_PARSE_COMMAND                (458)
#define F_PRESENT                      (459)
#define F_PRESENT_CLONE                (460)
#define F_PRINTF                       (461)
#define F_READ_BYTES                   (462)
#define F_READ_FILE                    (463)
#define F_REGMATCH                     (464)
#define F_REMOVE_INPUT_TO              (465)
#define F_REPLACE_PROGRAM              (466)
#define F_RMEMBER                      (467)
#define F_SAVE_OBJECT                  (468)
#define F_SAVE_VALUE                   (469)
#define F_SAY                          (470)
#define F_SHA1                         (471)
#define F_SNOOP                        (472)
#define F_SORT_ARRAY                   (473)
#define F_SPRINTF                      (474)
#define F_SSCANF                       (475)
#define F_STRFTIME                     (476)
#define F_TELL_ROOM                    (477)
#define F_TERMINAL_COLOUR              (478)
#define F_TO_BYTES                     (479)
#define F_TO_STRUCT                    (480)
#define F_TO_TEXT                      (481)
#define F_TO_TYPE                      (482)
#define F_TRIM                         (483)
#define F_UNIQUE_ARRAY                 (484)
#define F_VARIABLE_EXISTS              (485)
#define F_WALK_MAPPING                 (486)
#define F_WRITE_FILE                   (487)

/************************************************************************/

#endif /* INSTRS_H__ */
